import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={"bg-[url('../../public/turtles.svg')] bg-no-repeat bg-cover bg-center min-h-screen"}>
      <body>
        {children}
      </body>
    </html>
  );
}
